### ISSUE TITLE
Cannot find module 'phusion_passenger/line_reader'

### ISSUE THREAD

**Issue by carlitux** [phusion/passenger#1665]
```bash
App 31118 stderr: Error: Cannot find module 'phusion_passenger/line_reader'
App 31118 stderr:     at Function.Module._resolveFilename (module.js:337:15)
App 31118 stderr:     at Function.Module._load (module.js:287:25)
App 31118 stderr:     at Module.require (module.js:366:17)
App 31118 stderr:     at require (module.js:385:17)
App 31118 stderr:     at Object.<anonymous> (/usr/share/passenger/helper-scripts/node-loader.js:34:18)
App 31118 stderr:     at Module._compile (module.js:435:26)
App 31118 stderr:     at Object.Module._extensions..js (module.js:442:10)
App 31118 stderr:     at Module.load (module.js:356:32)
App 31118 stderr:     at Function.Module._load (module.js:311:12)
App 31118 stderr:     at Function.Module.runMain (module.js:467:10)
```
```bash
ls /usr/share/passenger/node/phusion_passenger
line_reader.js
```

Ubuntu trusty
passenger installed from repository

**Comment by FooBarWidget** [comment]
Which Node.js version are you using?

**Comment by carlitux** [comment]
4.2.2

**Comment by carlitux** [comment]
I have to modify the NODE_PATH on nginx and that was the error...

Using ansible with this line fixed the error.

passenger_env_var NODE_PATH /usr/share/passenger/node:{{ git_app_copy }}/app:{{ git_app_copy }}/frontend/javascript:{{ git_app_copy }}/lib;

**Comment by DanielZhu** [comment]
hi guys... I cannot find this folder /usr/share/passenger on my macOS, others all looks correct, then I got the same error Error: Cannot find module 'phusion_passenger/line_reader', as there's no line_reader.js at all...

And I tried to reinstall nginx via `brew reinstall nginx --with-passenger`, not worked... still cannot find folder `passenger` under `/usr/share`

Anyone can tell me where is it...?

**Comment by CamJN** [comment]
@DanielZhu That file is at this path when Passenger is installed via homebrew: `/usr/local/opt/passenger/libexec/src/nodejs_supportlib/phusion_passenger/line_reader.js`

**Comment by DanielZhu** [comment]
@CamJN thank you for your comment
I'm trying to use Nginx + Passenger on my macOS, at the same time... our webapp(nodejs + passenger) works fine in Linux server...
Is there any difference between /usr/share/passenger/node(i don't have this) with the /usr/local/bin/node

If i don't set passenger_node_path in Nginx conf file, Passenger will use the global node bin file, it cannot work, and tell me: cannot find moduels 'xxxx'(xxx is the alias in webpack config file, it should not take effect here, but in linux server, it does work)

**Comment by CamJN** [comment]
Yeah there's a difference: `/usr/share/passenger/node` is the path to some shared node resources in a linux install of Passenger, and `/usr/local/bin/node` is a (link to an) node executable. You are conflating [`passenger_nodejs`](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_nodejs) and [`passenger_env_var NODE_PATH`](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_env_var).

`passenger_env_var NODE_PATH` tells node where to look for npm packages, it shouldn't generally need to be set, however there are certainly situations that can require it to be.

`passenger_nodejs` tells passenger which node executable to use to run your app.

Try not setting `passenger_env_var NODE_PATH` and only set `passenger_nodejs` to `/usr/local/bin/node` and then let me know how that goes.

**Comment by DanielZhu** [comment]
@CamJN I comment out `passenger_env_var` in nginx conf file and then add some symlinks under node_modules to resolve the alias what webpack resolve/alias did. Now it works as expect...

Thank you. 👍

**Comment by InTerestedOWL** [comment]
Hello together,
I am facing the similar issue.
I am Working on plesk obsidian 18.0.31, together with nginx and apache. 

When I want to access my nodejs-Express-App I am facing this issue:
`internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'phusion_passenger/line_reader'
Require stack:
- /usr/share/passenger/helper-scripts/node-loader.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/share/passenger/helper-scripts/node-loader.js:121:18)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/share/passenger/helper-scripts/node-loader.js' ]
}`

I have checked this path: ls /usr/share/passenger/node/phusion_passenger 
This is resulting in line_reader.js
So everything should be fine. A reinstall with plesk doesnt changed anything.

Node-Version is 12.0.4 and is located under /opt/plesk/node/12/bin/npm

I dont know further on. 

Where can I set any attribute, so that phusion finds the /usr/share/passenger/node/phusion_passenger/line_reader.js

Thanks in advance
