### ISSUE TITLE
Node Cluster logs after updating to v5.1.0

### ISSUE THREAD

**Issue by dr-dimitru** [phusion/passenger#1905]
## Issue report

**Are you sure this is a bug in Passenger?**
Not sure, this may be interpreted as an question. If it is not a bug, should I care about those logs? Is it safe to ignore it? This is definitely comes from latest release, as noted: `Passenger now reports when you try to use Node.js or Meteor clustering, and tries to continue with just a nonfunctional shim in place, so that if your code uses the clustering APIs your app may still work.`

**Question 1: What is the problem?**
Those logs appears on all node.js apps. After updating to v5.1.0 (*application code wasn't changed*) logs filled with dozens of messages like this for each app (similar lines is omitted):
```
App 25260 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
...
App 25260 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'kerberos'
App 25260 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
...
App 25130 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'kerberos'
```

1. I am not using Node Cluster
2. Running node v4.6.2
3. Debian 8
4. Passenger integrated with Nginx (installed from oss-binaries.phusionpassenger.com repository)

**Question 2: Passenger version and integration mode**:
- open source 5.1.0/nginx

**Question 3: OS or Linux distro, platform (including version)**:
- Debian 8 x64

**Question 4: Passenger installation method**:
 - [x] Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- Node.js 4.6.2. Two apps based on Meteor.js (build to node.js), other pure Node.js with some libs, not frameworks

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- Proxmox VE, Dedicated Server

**Comment by OnixGH** [comment]
The log complains that it cannot find modules 'kerberos' and 'bson-ext'. It seems to me that this is the real problem in your app, did you check those missing dependencies?

The shim/cluster text is new in 5.1.0, but it's only relevant if you really use the cluster module so in this case you can safely ignore it. We will look into making this more clear in the error message.

**Comment by dr-dimitru** [comment]
Hi @OnixGH ,

Here is dependencies if one of one-file servers (micro-service):

```js
;((function (root) {
  "use strict";
  const MongoClient  = require('mongodb').MongoClient;
  const cp           = require('child_process');
  const spawn        = cp.spawn;
  const http         = require('http');
  const urlParser    = require('url');
  const normalizeUrl = require('normalize-url');
  const md5          = require('md5');
  const net          = require('net');
  const request      = require('request');
  const mongoAddr    = process.env.MONGO_URL;

  MongoClient.connect(mongoAddr, (error, db) => {

    const requestListener = (req, res) => {
      /* .... */
      res.end();
    }

    const server = http.createServer(requestListener);
    server.timeout = 55000;
    server.on('error', err => {
      console.error(err.stack);
    });
    server.listen(3999);
  });
})(this));
```

No other libs is used, cluster is not used, full startup logs:
```
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'kerberos'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'kerberos'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'bson-ext'
App 4932 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'boon-ext'
```

**Comment by CamJN** [comment]
The errors about 'bson-ext' mean the mongo driver is trying to load a c++ parser, and failing. Like @OnixGH said, our warning is a bit overzealous right now and we'll tone it back a bit, but it isn't why you are seeing those errors.

**Comment by dr-dimitru** [comment]
@CamJN Stack-trace or filename will be helpful.

My original question is till unclear for me:
> should I care about those logs? Is it safe to ignore it?

Or `boon-ext` package is actually missing, and should be added? *Needs to be said - I've to installed those packages to project as dependency, as well as install them globally, those error still persists.*

**Comment by OnixGH** [comment]
@dr-dimitru as I said in my first message to you: "in this case you can safely ignore it."

**Comment by dr-dimitru** [comment]
@OnixGH @CamJN thank you guys. And thank you and Phusion team for awesome project.

**Comment by OnixGH** [comment]
@dr-dimitru thanks, you're welcome :)

Like @CamJN said the log is a little overzealous so we'll keep this issue open until we have it patched, and that should make the message disappear for you.

**Comment by majgis** [comment]
I'm seeing the following errors on upgrading to v5.1.0
```
App 5410 stderr: Failed to install shim to guard against the Meteorhacks Cluster package. Error: Cannot read property 'indexOf' of undefined
App 5410 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'internal/util'
App 5410 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module './build/Release/DTraceProviderBindings'
App 5410 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module './build/default/DTraceProviderBindings'
App 5410 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module './build/Debug/DTraceProviderBindings'
App 5410 stderr: Failed to install shim to guard against the Node Cluster module. Error: Cannot find module 'source-map-support'
```

I just wanted to confirm that all of these can be ignored, as suggested above for similar errors

**Comment by OnixGH** [comment]
@majgis yes, you can ignore them. The cluster module guard is just a helper that tries to warn people about using the incompatible cluster module, it doesn't matter if it fails, as long as you're not actually using the cluster module :)

One question though, the first error looks like it's something in the detection that could be improved, what node version are you running App 5140 on?

**Comment by majgis** [comment]
Node.js v6.9.2

**Comment by CamJN** [comment]
Hi @majgis would you mind trying the `src/helper-scripts/node-loader.js` from this branch (https://github.com/phusion/passenger/tree/node_warning_improvement), it may not yet fix your problem necessarily but it increases the amount of logging which will help us make this feature more resilient.

**Comment by majgis** [comment]
I updated to 5.1.1, here is what I see now:
```
App 931 stderr: Failed to install shim to guard against the Meteorhacks Cluster package. Due to: Cannot read property 'indexOf' of undefined. Your can safely ignore this warning if you are not using Meteorhacks Cluster package
App 931 stderr:         Node version: v6.9.2    Arguments: 1
App 931 stderr:         [0] '(function (exports, require, module, __filename, __dirname) { // Maintainers, keep in mind that ES1-style octal literals (`0666`) are not\n// allowed in strict mode. Use ES6-style octal literals inst
```

Thank you.

**Comment by dr-dimitru** [comment]
@majgis are you using `Cluster` package?

**Comment by majgis** [comment]
No.

**Comment by OnixGH** [comment]
@majgis thanks for the trace! The other warnings are gone, right?

This specific case was still unclear to us so we added the information trace in 5.1.1 (and made the message less threathening). From the trace it's now clear to us how to tackle this, so we'll mop it up in the next release.

**Comment by majgis** [comment]
Correct, the other cluster warnings are gone, this is the only one.  Thanks, I'll lookout for the next release.

**Comment by dr-dimitru** [comment]
@OnixGH needs to be mention actually those logs is helped me a lot.
Idk why I haven't seen those errors on other stages (dev, testing), and that's weird.
It's helped to properly setup and use binaries form NPM packages,, like `bson`, `mcrypt`, `node-gyp`

So, I'm not sure if those logs should be fully removed .
I'm still on `5.1.0` and after solving NPM dependencies and its binaries issue - all warnings is gone.

I believe we need to test/investigate this more deeply.

**Comment by OnixGH** [comment]
@dr-dimitru I would guess that the modules you mention are optional modules, for which the parent silently swallows the require errors. For example, if you do:
```
var test;
try {
   test = require ('nonexistent');
} catch (e) {
// swallow silently
}
```
..then in 5.1.0 you will get a warning (because Passenger sees the original exception), but the rest of the code  will still work (as long as it doesn't try to use test).

As you can imagine in this case, the code that swallows the exception silently is probably doing it on purpose and doesn't want you to see it (so revealing it with Passenger can cause unnecessary worries).

You can easily copy the 5.1.0 Passenger trick if you do want to spy on this kind of stuff though; something like:
```
var Module = require('module');
var originalRequire = Module.prototype.require;
Module.prototype.require = function() {
  try {
    return originalRequire.apply(this, arguments);
  } catch (e) {
    console.trace(e);
    throw e;
  }
}
```

**Comment by OnixGH** [comment]
@majgis 5.1.2 was released, which should resolve the final remaining unnecessary warnings you're getting. Let us know if you experience differently.

**Comment by majgis** [comment]
Thank you.  I tested it, and everything looks great.  I don't see any more stderr messages on startup.
