### ISSUE TITLE
bundle exec rails server does not work on rails 4.1.9 + mongoid 4.0.2

### ISSUE THREAD

**Issue by danarnold** [phusion/passenger#1768]
`bundle exec passenger start` works fine.

`bundle exec rails server` gives the following error:

```
/home/dan/.rvm/gems/ruby-2.2.3@project/gems/mongoid-4.0.2/lib/mongoid/railtie.rb:110:in `block in <class:Railtie>': undefined method `on_event' for PhusionPassenger:Module (NoMethodError)
```

Looking at the [mongoid source for that line](https://github.com/mongodb/mongoid/blob/v4.0.2/lib/mongoid/railtie.rb#L109), you can see that they call `.on_event`. My guess is that the code that ties Passenger into rails for using `rails server` loads things differently than the actual `passenger` command, causing `.on_event` to not be defined at that point in loading, and that is the reason for this not working.

**Comment by OnixGH** [comment]
Thanks for the report, our preliminary conclusion is the same, we'll schedule this one.

**Comment by OnixGH** [comment]
https://github.com/phusion/passenger/commit/fcf173eaaee0d4436cbe89b1da2b187191e04abe was missing to complete the fix.
