### ISSUE TITLE
Passenger 3 does not build on Ubuntu  10.04

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#632]
_From [tony.primerano](https://code.google.com/u/100553129460639203862/) on September 20, 2010 20:32:20_

What steps will reproduce the problem? 1. rvm 1.9.2
2. rails 3.0.0
3. gem install passenger --pre
4. sudo apt-get install libcurl4-openssl-dev
5. rvmsudo passenger-install-nginx-module What is the expected output? What do you see instead? Build fails with
Curl development headers with SSL support... not found What version of Phusion Passenger are you using? Which version of Rails? On what operating system? Passenger 3.0.0 beta 2
Rails 3.0.0
Ubuntu  10.04 Please provide any additional information below. from gist. http://gist.github.com/587853 If I remove the unlink of the /tmp/passenger-curl-check.c (from passenger-3.0.0.pre2/lib/phusion_passenger/dependencies.rb) and run the compile command directly I get IDN errors

gcc -o '/tmp/passenger-curl-check' '/tmp/passenger-curl-check.c' -lcurl
/usr/lib/gcc/i486-linux-gnu/4.4.3/../../../../lib/libcurl.so: undefined reference to `idna_to_ascii_lz@LIBIDN_1.0'
/usr/lib/gcc/i486-linux-gnu/4.4.3/../../../../lib/libcurl.so: undefined reference to`tld_strerror@LIBIDN_1.0'
......

If I add -lidn it compiles fine

gcc -o '/tmp/passenger-curl-check' '/tmp/passenger-curl-check.c' -lcurl -lidn

--- curl config ----

> curl-config --libs
> -lcurl
> curl-config --version
> libcurl 7.19.7
> curl-config --features
> SSL
> IPv6
> libz
> IDN
> NTLM
> curl-config --static-libs
> /usr/lib/libcurl.a -lidn -lssl -lcrypto -llber -lldap -lrt -lgssapi_krb5 -lgssapi_krb5 -lssl -lcrypto -lz

I guess this is happening because --libs is not returning -lidn.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=533_
