### ISSUE TITLE
Nginx doesn't compile with GCC 4.6.* thanks to -Werror

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#788]
_From [sharagoz](https://code.google.com/u/118276109488840814568/) on July 05, 2011 15:02:49_

Installation through passenger-install-nginx-modules fails on Linux x86_64 with gcc 4.6.\* installed. It works fine with gcc 4.5.*. It seems to be related to the -Werror flag.

src/core/ngx_resolver.c: In function ‘ngx_resolver_process_ptr’:
src/core/ngx_resolver.c:1425:43: error: variable ‘qclass’ set but not used [-Werror=unused-but-set-variable]
src/core/ngx_resolver.c:1425:36: error: variable ‘qtype’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

make[1]: **\* [objs/src/core/ngx_resolver.o] Error 1
make[1]: Leaving directory `/tmp/root-passenger-28914/nginx-1.0.0'
make: **\* [build] Error 2

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=689_
