### ISSUE TITLE
passenger-install-apache2-module passes checks but fails to build on Ubuntu 16.04 without libssl-dev installed

### ISSUE THREAD

**Issue by rockorequin** [phusion/passenger#1934]
I installed the Passenger 5.1.2 gem on Ubuntu 16.04 x86_64 using the ruby that comes in the Ubuntu repositories (ruby 2.3.1p112) and the "gem install passenger" command, and tried to build the apache module using passenger-install-apache2-module, selecting ruby and not python. However, although it passed the OpenSSL Ruby support check:

     * Checking for OpenSSL support for Ruby...
          Found: yes

it failed to build, giving the error:

    In file included from src/agent/Core/SecurityUpdateChecker.h:17:0,
                     from src/agent/Core/CoreMain.cpp:94:
    src/cxx_supportlib/Crypto.h:37:25: fatal error: openssl/pem.h: No such file or directory

After installing the libssl-dev package (sudo apt install libssl-dev), it built without any issues.

**Comment by CamJN** [comment]
Thanks for pointing this out, looks like we missed updating one of the dependency checkers.
