### ISSUE TITLE
Doesn't compile on GCC 4.6 (missing -lm for linking phase ends in libm.so: could not read symbols: Invalid operation)

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#803]
_From [adriandcs](https://code.google.com/u/104501441707187581097/) on September 06, 2011 01:28:43_

What steps will reproduce the problem? 1.gem install passenger
2.go to your rails app
3.passenger start

I'm in Ubuntu 11.10 (beta1) 64bits, passenger (3.0.9), Rails 3.0.10.

After passenger start there is some errors displayed on screen, but the interesting part is this (if you need the full log I can paste it here).

But maybe this is enough:

objs/ngx_modules.o \
        -lpthread -lcrypt -lm /home/victor/.passenger/standalone/3.0.9-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/ext/nginx/../common/libpassenger_common.a /home/victor/.passenger/standalone/3.0.9-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/ext/nginx/../common/libboost_oxt.a -lstdc++ -lpthread -lcrypto -lcrypto -lz
/usr/bin/ld: /home/victor/.passenger/standalone/3.0.9-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/ext/nginx/../common/libpassenger_common.a(aggregate.o): undefined reference to symbol 'round@@GLIBC_2.2.5'
/usr/bin/ld: note: 'round@@GLIBC_2.2.5' is defined in DSO /usr/lib/gcc/x86_64-linux-gnu/4.6.1/../../../x86_64-linux-gnu/libm.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-linux-gnu/4.6.1/../../../x86_64-linux-gnu/libm.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[1]: **\* [objs/nginx] Error 1
make[1]: se sale del directorio «/tmp/victor-passenger-standalone-25482/nginx-1.0.6»
make: **\* [build] Error 2

If you note there, there is this line that reads:
-lstdc++ -lpthread -lcrypto -lcrypto -lz

maybe what you meant was:
-lstdc++ -lpthread -lcrypto -lm -lz

Not -lcrypto twice?

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=704_
