### ISSUE TITLE
passenger-irb: undefined method 'obtain_read_only_admin_password'

### ISSUE THREAD

**Issue by felixbuenemann** [phusion/passenger#1552]
The `passenger-irb` command is broken in at least 5.0.10 and 5.0.11:

```
/usr/sbin/passenger-irb:126:in `query_and_parse_pool_xml': undefined method `obtain_read_only_admin_password' for #<PhusionPassenger::IrbTool:0x0000000264b070> (NoMethodError)
	from /usr/sbin/passenger-irb:117:in `block in find_first_app'
	from /usr/sbin/passenger-irb:116:in `each'
	from /usr/sbin/passenger-irb:116:in `find_first_app'
	from /usr/sbin/passenger-irb:95:in `select_process'
	from /usr/sbin/passenger-irb:41:in `run'
	from /usr/sbin/passenger-irb:304:in `<main>
```

**Comment by FooBarWidget** [comment]
Thanks for reporting this. It looks like the sudo-less admin tools change broke passenger-irb. We'll get this fixed asap.

**Comment by FooBarWidget** [comment]
Version 5.0.12 has been released with this bug fixed.

**Comment by dewolfe** [comment]
Great thank you so much for the quick fix!

**Comment by dewolfe** [comment]
I am guessing it will hit the PPA a little bit later.

**Comment by felixbuenemann** [comment]
Thanks for the quick fix. It's working fine on 5.0.12.
